// RF-12
DROP INDEX INDEX_LC_COD_ADMINISTRADOR;
DROP INDEX INDEX_PD_COD_USUARIO;
DROP INDEX INDEX_PD_FECHA_CREACION;
DROP INDEX INDEX_PD_FECHA_ENTREGA;

// RF-13
DROP INDEX INDEX_PL_COD_LUGAR_ALMAC;
DROP INDEX INDEX_PL_COD_PRESENTACION;
DROP INDEX INDEX_LA_COD_TIPO_PRODUCTO;

// RF-14, RF-15
DROP INDEX INDEX_MB_COD_LUGAR_ORIGEN;
DROP INDEX INDEX_MB_COD_LUGAR_DESTINO;
DROP INDEX INDEX_MB_FECHA_MOVIMIENTO;
DROP INDEX INDEX_MB_COD_PRODUCTO;
DROP INDEX INDEX_MB_COD_PRESENTACION;
DROP INDEX INDEX_MB_CANTIDAD;
